package com.terminads.mm.secondscreen

/**
 * GENERATED FILE -- do not edit by hand.
 *
 * Source: mm/include/tables/scene_table.h, humanName column (2S2H's curated
 * names, the same ones Better Map Select shows). Ordinal position in that
 * X-macro table is the sceneId. Regenerate after any scene-table change with:
 *
 *   python3 tools/generate-scene-names.py
 *
 * Unset ordinals (DEFINE_SCENE_UNSET) are absent: forId returns null and the
 * HUD falls back to "SCENE <id>" rather than guessing.
 */
object SceneNames {
    fun forId(sceneId: Int): String? = TABLE[sceneId]

    val size: Int get() = TABLE.size

    private val TABLE: Map<Int, String> = mapOf(
        0 to "Southern Swamp (Clear)",
        7 to "Lone Peak Shrine & Grottos",
        8 to "Cutscene Scene",
        10 to "Magic Hags' Potion Shop",
        11 to "Majora's Lair",
        12 to "Beneath the Graveyard",
        13 to "Curiosity Shop",
        16 to "Mama's House & Barn",
        17 to "Honey & Darling's Shop",
        18 to "The Mayor's Residence",
        19 to "Ikana Canyon",
        20 to "Pirates' Fortress",
        21 to "Milk Bar",
        22 to "Stone Tower Temple",
        23 to "Treasure Chest Shop",
        24 to "Inverted Stone Tower Temple",
        25 to "Clock Tower Rooftop",
        26 to "Before Clock Town",
        27 to "Woodfall Temple",
        28 to "Path to Mountain Village",
        29 to "Ancient Castle of Ikana",
        30 to "Deku Scrub Playground",
        31 to "Odolwa's Lair",
        32 to "Town Shooting Gallery",
        33 to "Snowhead Temple",
        34 to "Milk Road",
        35 to "Pirates' Fortress Interior",
        36 to "Swamp Shooting Gallery",
        37 to "Pinnacle Rock",
        38 to "Fairy's Fountain",
        39 to "Swamp Spider House",
        40 to "Oceanside Spider House",
        41 to "Astral Observatory",
        42 to "Moon Deku Trial",
        43 to "Deku Palace",
        44 to "Mountain Smithy",
        45 to "Termina Field",
        46 to "Post Office",
        47 to "Marine Research Lab",
        48 to "Beneath Graveyard and Dampe's House",
        50 to "Goron Shrine",
        51 to "Zora Hall",
        52 to "Trading Post",
        53 to "Romani Ranch",
        54 to "Twinmold's Lair",
        55 to "Great Bay Coast",
        56 to "Zora Cape",
        57 to "Lottery Shop",
        59 to "Pirates' Fortress Moat",
        60 to "Fisherman's Hut",
        61 to "Goron Shop",
        62 to "Deku King's Chamber",
        63 to "Moon Goron Trial",
        64 to "Road to Southern Swamp",
        65 to "Doggy Racetrack",
        66 to "Cucco Shack",
        67 to "Ikana Graveyard",
        68 to "Goht's Lair",
        69 to "Southern Swamp (poison)",
        70 to "Woodfall",
        71 to "Moon Zora Trial",
        72 to "Goron Village (spring)",
        73 to "Great Bay Temple",
        74 to "Waterfall Rapids",
        75 to "Beneath the Well",
        76 to "Zora Hall Rooms",
        77 to "Goron Village (winter)",
        78 to "Goron Graveyard",
        79 to "Sakon's Hideout",
        80 to "Mountain Village (winter)",
        81 to "Ghost Hut",
        82 to "Deku Shrine",
        83 to "Road to Ikana",
        84 to "Swordsman's School",
        85 to "Music Box House",
        86 to "Igos du Ikana's Lair",
        87 to "Tourist Information",
        88 to "Stone Tower",
        89 to "Inverted Stone Tower",
        90 to "Mountain Village (spring)",
        91 to "Path to Snowhead",
        92 to "Snowhead",
        93 to "Path to Goron Village (winter)",
        94 to "Path to Goron Village (spring)",
        95 to "Gyorg's Lair",
        96 to "Secret Shrine",
        97 to "Stock Pot Inn",
        98 to "Great Bay Cutscene",
        99 to "Clock Tower Interior",
        100 to "Woods of Mystery",
        101 to "Lost Woods (Intro)",
        102 to "Moon Link Trial",
        103 to "The Moon",
        104 to "Bomb Shop",
        105 to "Giants' Chamber",
        106 to "Gorman Track",
        107 to "Goron Racetrack",
        108 to "East Clock Town",
        109 to "West Clock Town",
        110 to "North Clock Town",
        111 to "South Clock Town",
        112 to "Laundry Pool",
    )
}
